### PR TITLE
Fix inconsistency "theme" vs. "plugin"

### PR DESCRIPTION
**Pull request by vlad-timotei**
I can only assume it's "This theme", but it definitely can't be different btw singular and plural form. :D

### CODE REVIEW

**Comment by rlankhorst** [comment]
@vlad-timotei Hi Vlad, Thanks for the input. It should be "plugin", both in singular as plural, as it's Complianz GDPR doing the recommendation.

**Comment by vlad-timotei** [comment]
Awesome, then in other places in that file it should be also plugin "instead" of  "theme", right?

Same file, for 
- notice_can_install_required line 341
- notice_ask_to_update line 353
- plugin_needs_higher_version line 399

**Comment by rlankhorst** [comment]
@vlad-timotei yes, but these others are not applicable, as these do not apply in any of the uses cases in the plugin. So we can ignore these.

**Comment by vlad-timotei** [comment]
All right. Thank you for the info. 😃

**Comment by rlankhorst** [comment]
Looking in the code, I think it will always get overwritten by this string:
https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/e01c6928e59009d3eacb9d57fc5c4051610d8a4a/integrations/TGM/required.php#L135

So should never apply anyway.

**Pull request closed without merging**
