### PR TITLE
Fix AddToAny plugin integration

### PR DESCRIPTION
**Pull request by micropat**
AddToAny author here. 👋

This fixes a Complianz integration bug where AddToAny's _plugin_ script is erroneously targeted instead of AddToAny's _hosted_ script. The side effect of this bug is that it's breaking AddToAny's configuration on sites because `window.a2a_config` isn't parsed in time.

AddToAny's category is also corrected as `functional` instead of `marketing` since no marketing cookies are used and [the policy](https://www.addtoany.com/privacy) is to _not_ track users.

### CODE REVIEW

**Comment by rlankhorst** [comment]
hi @micropat thanks for your input. 

What is the functional difference between the plugin script and the hosted script? Am I correct that your service loads social media like Facebook etc? In that case the result of loading addtoany would be to load Facebook for example, which tracks users. Consent is required, and the category should be marketing. 

If both script load the facebook button, both need to be blocked. 

I see in your privacy statement the following:
_In a URL request, typical server log data may be shared with service providers and partners.
Official service integrations are served by their respective services under their respective privacy policies.
For example, the Facebook Like button is hosted & served by Facebook under their privacy policy._

This suggests that even without looking at Facebook, data is shared with service providers and partners. The data that is shared includes personal data like ip numbers. It is also not clear in the privacy statement what data is stored in the cookies that are stored on your domain.

But unless it is possible to unlock Facebook separately in the widget, it is not possible to allow AddtoAny under the functional category. 

Let me know if I'm wrong.

**Comment by rlankhorst** [comment]
I don't think I can prevent addtoany from loading Facebook if it is inserting it dynamically. Unless I can stop that somehow I have to prevent addtoany from loading at all.

Do I understand you correctly that you always load both scripts, but the hosted script is responsible for the loading of the social media?

If the local hosted script does not load third party scripts at all it can load, as long as it does not have a dependency on the hosted one.

We'll set up some tests to check. This integration hasn't been touched in years. I know it originally worked fine: blocking the social media, and loading on consent.

**Comment by rlankhorst** [comment]
@micropat as there can be several social media activated by addtoany, all dynamically through javascript, it's hard to manage that from our side when the script is already running. But if you would for example check for consent if you detect complianz, with cmplz_has_consent('marketing'), then this would work. 

A more generic solution could be to integrate the WP Consent API into AddToAny, https://wordpress.org/plugins/wp-consent-api/ which we implemented with cookiebot. 

The idea behind this plugin is that it can eventually become part of WordPress core, and function as a consent api between plugins like complianz and cookiebot on the one side, and plugins like AddToAny on the other side.

**Comment by rlankhorst** [comment]
Sounds great! Thanks 👍

**Comment by AertHulsebos** [comment]
@micropat @rlankhorst Consent API integration seems great! Both will be introduced in 7.0, currently being tested. I have merged both in our Beta version. regards Aert

**Comment by rlankhorst** [comment]
We'll include it in our next release as well then, should be live early next week for free, this week for premium.

**Comment by rlankhorst** [comment]
@micropat for a quick solution for your users: if they disable the addtoany integration in complianz/integrations, the script won't be blocked anymore. 

After the next update this won't be necessary.

**Comment by rlankhorst** [comment]
Hi @micropat,

The consent api condition here means the plugin won't block AddToAny at all if the Consent Api is enabled. 

We did it this way to ensure that it's still compliant if the Consent Api is not enabled.

This means that when the Consent Api is active this block array and its marketing category designation is not loaded at all, and AddToAny can load normally.

My guess would be this publisher didn't have the consent api active, is that correct?

**Comment by rlankhorst** [comment]
@micropat Ah! This wasn't clear to me, I thought there only was the Consent API integration. 

I will remove the block list entirely then.

**Comment by rlankhorst** [comment]
@micropat This wasn't clear to me yet, that you also integrated with Complianz directly. I will remove the blocklist, then our legal testers will test the results. 

I'll get back to you on this.

Another question: we always test with the AddToAny wordpress plugin, but have never seen a javascript error when blocked. What is the configuration used that results in this error? That would enable us to test better.

**Pull request closed without merging**
