### PR TITLE
A11y: fix buttons and links accessibility

### PR DESCRIPTION
**Pull request by juliemoynat-tanaguru**
Hi,

This is a PR to fix the accessibility for buttons and links: links go somewhere and buttons do something.

* The `aria-label` attribute is useless where it has been used in the plugin as it's duplicating the content inside the button or link or it is totally different. If the link or button has a relevant visible text, `aria-label` should not be used.
* I've added `role="button"` attribute where links are actually buttons.
* I've removed `tabindex` attribute where links have a `href` attribute because it is useless in this case.
* I've transform the revoke button into a real HTML button instead of a `div` so that is accessible through keyboard now.
* I've transform the cookie consent description into a `div` instead of a `span` because it's containing WYSIWYG content with paragraphs (a `span` cannot contain `p` or other HTML block elements).

### CODE REVIEW

**Comment by rlankhorst** [comment]
@juliemoynat-tanaguru this branch has been merged into the 5.0 branch, which will get merged into master soon.

**Comment by juliemoynat-tanaguru** [comment]
I'm sad this PR was closed whereas the problems seem to still be there inside JS files at the moment…

**Comment by rlankhorst** [comment]
@juliemoynat-tanaguru this has been closed because it has been merged in the 5.0 branch. You can check the 5.0 branch to see if it's fixed

**Comment by juliemoynat-tanaguru** [comment]
@rlankhorst Oh I'm sorry, I thought the 5.0 version was the current version.

I can see some problems in v5 in the three JS files:

- on line 231, this code is still there `aria-label="learn more about cookies" role=button tabindex="0"` and should not: https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/5.0/assets/js/cookieconsent.js#L231
- on line 570, in this code `<a role="button" class="cc-link cookie-policy" href="{{href}}" target="_blank">{{link}}</a>` there shouldn't be a `role="button"` because it's a real link, not a button: https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/5.0/assets/js/cookieconfig-styling.js#L570
- on lines 836, 837 and 839, there are two `role="button"` attributes on each button: https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/5.0/assets/js/complianz.js#L836

Thank you

**Comment by rlankhorst** [comment]
@juliemoynat-tanaguru I have fixed those as well, it has now been merged to master, as we're almost releasing 5.0.

**Comment by juliemoynat-tanaguru** [comment]
@rlankhorst Perfect! Thank you so much.

**Pull request closed without merging**
